server:
  context-path: /gamedog
  port: 8888

debug: true

# THYMELEAF
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5

# DataSource
spring:
  datasource:
    url: jdbc:mysql://119.188.247.170/dl_adb_all?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mRHLRjCkPD6X56nP
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  mapperLocations: classpath*:mapper/*.xml
